/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rock.frame;

import Rock.frame.selectModeFrame;

/**
 *
 * @author ouu
 */
public class dialogJFrame extends javax.swing.JFrame {

    /**
     * Creates new form dialogJFrame
     */
    public dialogJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finalStatement = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        again = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finalStatement.setFont(new java.awt.Font("华文彩云", 0, 24)); // NOI18N
        finalStatement.setText("恭喜你获得了本次游戏的胜利！");
        getContentPane().add(finalStatement, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 340, 40));

        close.setBackground(new java.awt.Color(242, 247, 225));
        close.setFont(new java.awt.Font("华文彩云", 1, 18)); // NOI18N
        close.setText("结束游戏");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 339, -1, 40));

        again.setBackground(new java.awt.Color(150, 218, 226));
        again.setFont(new java.awt.Font("华文彩云", 1, 18)); // NOI18N
        again.setText("再来一局");
        again.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againActionPerformed(evt);
            }
        });
        getContentPane().add(again, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 337, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 600));
        jLabel1.getAccessibleContext().setAccessibleName("bg");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *   结束游戏
     */
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    /**
     *   再来一局
     */
    private void againActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againActionPerformed
        dispose();
        new selectModeFrame().createSelectModeFrame();
    }//GEN-LAST:event_againActionPerformed

    /**
     *   设置弹框dialog的文本内容
     * @param battleMode 游戏模式
     * @param winner 游戏的最后赢家名字
     */
    public void setFinalStatement(String battleMode, String winner) {
        if ("Man VS Computer".equals(battleMode)) {
            switch (winner) {
                case "man":
                    finalStatement.setText("恭喜你赢得了本次游戏的胜利！");
                    break;
                case "computer":
                    finalStatement.setText("很遗憾你输了游戏，再接再厉！");
                    break;
                default:
                    finalStatement.setText("好厉害，居然和电脑打成平手！");
                    break;
            }
        } else {
            if ("equal".equals(winner)) {
                finalStatement.setText("两位玩家不分上下，游戏平局！");
            } else {
                finalStatement.setText("恭喜" + winner + "赢得了本次游戏！");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton again;
    private javax.swing.JButton close;
    private javax.swing.JLabel finalStatement;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
