/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rock.frame;

import java.awt.Toolkit;

/**
 *
 * @author ouu
 */
public class selectModeFrame extends javax.swing.JFrame {

    private String battleMode = "";

    public int width = Toolkit.getDefaultToolkit().getScreenSize().width;
    public int height = Toolkit.getDefaultToolkit().getScreenSize().height;
    public int windowsWedth = 800;
    public int windowsHeight = 630;

    /**
     * Creates new form selectModeFrame
     */
    public selectModeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manVSman = new javax.swing.JButton();
        manVScomputer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 238));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("华文彩云", 0, 36)); // NOI18N
        jLabel1.setText("Rock paper scissors");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 320, 40));

        manVSman.setBackground(new java.awt.Color(242, 247, 225));
        manVSman.setFont(new java.awt.Font("华文彩云", 1, 18)); // NOI18N
        manVSman.setText("Man VS Man");
        manVSman.setActionCommand("manVSman");
        manVSman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manVSmanActionPerformed(evt);
            }
        });
        getContentPane().add(manVSman, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 289, 63));

        manVScomputer.setBackground(new java.awt.Color(150, 218, 226));
        manVScomputer.setFont(new java.awt.Font("华文彩云", 1, 18)); // NOI18N
        manVScomputer.setText("Man VS Computer");
        manVScomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manVScomputerActionPerformed(evt);
            }
        });
        getContentPane().add(manVScomputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 289, 66));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 82, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));
        bg.getAccessibleContext().setAccessibleName("bg");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @description 选择人人对战模式
     */
    private void manVSmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manVSmanActionPerformed
        battleMode = "Man VS Man";
        createRoundFrame();
    }//GEN-LAST:event_manVSmanActionPerformed

    /**
     * @description 选择人机对战模式
     */
    private void manVScomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manVScomputerActionPerformed
        battleMode = "Man VS Computer";
        createRoundFrame();
    }//GEN-LAST:event_manVScomputerActionPerformed

    /**
     * @description 创建选择回合数窗口
     */
    public void createRoundFrame() {
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                roundJFrame round = new roundJFrame();
                round.getBattleMode(battleMode);
                round.setTitle(" 选择回合数目");
                round.setBounds((width - windowsWedth) / 2, (height - windowsHeight) / 2, windowsWedth, windowsHeight);
                round.setVisible(true);
                round.setResizable(false);
            }
        });
    }

    /**
     * @description 创建选择游戏模式数窗口的一些额外设定
     */
    public void createSelectModeFrame() {
            selectModeFrame selectBattleMode = new selectModeFrame();
            selectBattleMode.setTitle(" 选择对战模式");
            selectBattleMode.setBounds((width - windowsWedth) / 2, (height - windowsHeight) / 2, windowsWedth, windowsHeight);
            selectBattleMode.setVisible(true);
            selectBattleMode.setResizable(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> {
            new selectModeFrame().createSelectModeFrame();
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manVScomputer;
    private javax.swing.JButton manVSman;
    // End of variables declaration//GEN-END:variables
}
